### ISSUE TITLE
Selection not working on mousedown

### ISSUE THREAD

**Issue by jitenderchand** [kapilkashyap/jquery-paginated-dropdown-widget#1] opened 2016-01-11 09:33 UTC
When you press and hold the mouse on dropdown list. Then list is hiding and selection is not working

**Comment by jitenderchand** [comment] 2016-01-11 12:52
replacing click with mousedown in plugin file work for me. just wanted to know is that is fine or we could have done it in more better way

**Comment by kapilkashyap** [comment] 2016-01-12 02:34
Hi jitenderchand,

I just tested it real quick and it works just fine. Are you talking about the demo page or this is happening during integration into your application?

It would be great if you provide more details like jQuery version, browser, OS, if you are using any other 3rd party libraries? Sometimes few events are blocked by some libraries, looks like click event might be blocked on few elements.

Please provide as much detail as you can.

Thanks.

**Comment by jitenderchand** [comment] 2016-01-12 02:48
Hi Kapil,

Click event is working fine however the issue  with mousedown event. On
demo page just press the mouse on list(don't release the mouse). You can
see the problem.

**Comment by kapilkashyap** [comment] 2016-01-12 04:38
Hi jitenderchand,

That is by design. Once one has selected an item, the drop down simply closes. That's how a simple select also works.

But yeah, point taken. We can make that configurable. The developer can decide which event to use. If one does not provide any, click would be the default.

Hope this answers your question/concern.

Regards.

**Comment by jitenderchand** [comment] 2016-01-12 04:44
Thanks Kapil.

**Comment by kapilkashyap** [comment] 2016-01-12 06:38
Will add an enhancement, closing this issue!

**Closed as completed by kapilkashyap** 2016-01-12 06:38 UTC
